### ISSUE TITLE
[FEATURE] `flutter_map` feature parity

### ISSUE THREAD

**Issue by josxha** [josxha/flutter-maplibre#32]
### Feature Description

This issue tracks feature parity between [josxha/flutter-maplibre](https://github.com/josxha/flutter-maplibre) and [fleaflet/flutter_map](https://github.com/fleaflet/flutter_map).
Features provided only by josxha/flutter-maplibre are not listed.

## Supported platforms
- [x] android
- [ ] iOS
- [ ] windows
- [ ] macOS
- [ ] linux
- [x] web

## Map
- [x] set a map boundary
- [x] min and max zoom level
- [x] background color
- [x] initial center by lat/long
- [ ] initial center by bounding box
- [x] initial rotation, initial zoom

## Map camera
- [x] current bounding box
- [x] current zoom, map center and camera rotation

## Map controller
- [x] move and rotate the map
- [ ] rotate around point
- [x] fit map camera inside a bounding box
- [x] move the map camera to that all coordinates of a list are visible

## Gestures
- [x] double tap and drag to zoom
- [x] double tap zoom
- [x] drag
- [x] fling
- [x] disable some or all gestures
- [x] two finger gestures
- [x] zoom with scroll wheel
- [x] zoom with CTRL key and drag

## CRS
- [x] convert coordinates to screen locations and vice versa
- [x] EPSG:3857 (Web Marcator projection)
- [ ] EPSG:4326
- [ ] custom CRS

## Tile layer
- [x] raster tiles
- [x] fade in tiles
- [ ] load tiles from flutter assets
- [x] load tiles from network
- [x] load tiles from WMS tile provider
- [x] fallback url for tile provider
- [x] specify the tile size / retina mode
- [x] min and max zoom the tile layer gets displayed
- [x] min and max zoom the tile provider supports
- [x] TMS tile sources
- [x] zoom offset
- [ ] tile buffer around the viewport of the map
- [ ] custom tile builder
- [x] bounds of the tile source
- [ ] set user agent

## Circle layer
- [x] border stroke width
- [x] color
- [x] radius
- [x] use radius in meter (convert it to a fill layer)
- [x] click callback

## Marker layer
- [x] display images
- [x] display flutter widgets
- [x] marker alignment
- [x] rotate marker together with map
- [x] click callback

## Polygon layer
- [x] border color
- [x] border stroke width
- [x] fill color
- [x] disable borders for holes
- [x] polygons with holes
- [x] polygon label
- [x] dotted or dashed border (border pattern)
- [x] rotate polygon label with map rotation
- [x] click callback

## Polyline layer
- [x] stroke width
- [x] stroke pattern
- [x] stroke color
- [x] line outline (use 2nd line layer beneath)
- [x] line outline color
- [x] line outline width
- [x] stroke width in meters (use a fill layer)

## Overlay image layer
- [x] position image on the map
- [x] image opacity
- [ ] rotate and distort image

## Map events
- [ ] double tap zoom start, end
- [ ] fling gesture, start, end, fling not started
- [x] long press, https://github.com/josxha/flutter-maplibre/pull/34
- [x] camera move, move start, move end
- [ ] widget size changed
- [ ] map rotated, start, end
- [ ] scroll wheel zoom
- [x] secondary tap, https://github.com/josxha/flutter-maplibre/pull/34
- [x] map tapped, https://github.com/josxha/flutter-maplibre/pull/34

## Other features by the core package
- [x] source attribution
- [x] scale bar

## Features provided by flutter_map plugins
- [ ] draggable marker
- [x] geojson
- [x] user location
- [x] marker clusters
- [ ] marker popup
- [x] animated lines
- [x] compass showing the map rotation
- [x] heatmap
- [x] vector tiles
- [x] tile caching
- [ ] pmtiles
- [x] mbtiles
- [x] animated movements
- [x] bulk downloading

**Comment by jesussmile** [comment]
Do we have mbtiles examples for this ? If yes I could shift my app to maplibre ?

**Comment by josxha** [comment]
@jesussmile not yet, unfortunally. There are two different ways to use a MBTiles archive:

1. Download a MBTiles file and import it into the main database using `OfflineManager.mergeOfflineRegions()` (available on the main branch or in the future version 0.1.2).
2. Use mbtiles as a tile source in your map style like described in [this article](https://medium.com/@ty2/how-to-display-offline-maps-using-maplibre-mapbox-39ad0f3c7543).

**Comment by josxha** [comment]
Closing this issue of now. Missing functionality can be tracked in separate feature requests.
